server {
    listen 80;
    location /api/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_pass http://backend:8000/api/;
    }
    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_pass http://backend:8000/admin/;

    }
    location / {
        alias /staticfiles/;
        index index.html;
    }
}